# Generated by Django 4.2.1 on 2023-05-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
