# Generated by Django 4.2.1 on 2023-06-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
