# Generated by Django 4.2.1 on 2023-06-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0002_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telephone_area_code',
            new_name='areaCode',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telephone_number',
            new_name='telephone',
        ),
    ]
