# Generated by Django 4.2.1 on 2023-05-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0002_alter_book_pages_alter_book_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id_publisher',
            new_name='publisher',
        ),
    ]
