# Generated by Django 4.2.1 on 2023-06-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0003_rename_telephone_area_code_profile_areacode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address_province',
            new_name='province',
        ),
    ]
